/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_sniffer_Sniffer_Sniffer */

#ifndef _Included_com_jupiter_sniffer_Sniffer_Sniffer
#define _Included_com_jupiter_sniffer_Sniffer_Sniffer
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_tencent_sniffer_Sniffer_Sniffer
 * Method:    nativeSniff
 * Signature: (Lcom/tencent/sniffer/Sniffer/Sniffer/Options;)I
 */
JNIEXPORT jint JNICALL Java_com_jupiter_snifferframework_Sniffer_nativeSniff
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tencent_sniffer_Sniffer_Sniffer
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jupiter_snifferframework_Sniffer_nativeStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
